<?php
$config = array (
  'baseurlpath' => 'libraries/simplesamlphp/www/',
  'certdir' => 'cert/',
  'loggingdir' => '/home/volj/test.volunteers.joomla.org/www/logs/',
  'datadir' => 'data/',
  'tempdir' => '/home/volj/test.volunteers.joomla.org/www/tmp/',
  'technicalcontact_name' => 'Joomla',
  'technicalcontact_email' => 'admin@joomla.org',
  'timezone' => 'UTC',
  'secretsalt' => 'rV2WJupUfggPbSFXh5yP',
  'auth.adminpassword' => '5E\'|5557zJd0nu`8h[2q',
  'admin.protectindexpage' => true,
  'admin.protectmetadata' => false,
  'admin.checkforupdates' => false,
  'trusted.url.domains' => 
  array (
  ),
  'trusted.url.regex' => false,
  'enable.http_post' => false,
  'debug' => 
  array (
    'saml' => true,
    'backtraces' => true,
    'validatexml' => true,
  ),
  'showerrors' => true,
  'errorreporting' => true,
  'logging.level' => 7,
  'logging.handler' => 'file',
  'logging.format' => '%date{%b %d %H:%M:%S} %process %level %stat[%trackid] %msg',
  'logging.facility' => 168,
  'logging.processname' => 'simplesamlphp',
  'logging.logfile' => 'simplesamlphp.log',
  'statistics.out' => 
  array (
  ),
  'proxy' => NULL,
  'proxy.auth' => false,
  'enable.saml20-idp' => false,
  'enable.shib13-idp' => false,
  'enable.adfs-idp' => false,
  'enable.wsfed-sp' => false,
  'enable.authmemcookie' => false,
  'default-wsfed-idp' => 'urn:federation:pingfederate:localhost',
  'shib13.signresponse' => true,
  'session.duration' => 28800,
  'session.datastore.timeout' => 14400,
  'session.state.timeout' => 3600,
  'session.cookie.name' => 'SimpleSAMLSessionID',
  'session.cookie.lifetime' => 0,
  'session.cookie.path' => '/',
  'session.cookie.domain' => NULL,
  'session.cookie.secure' => false,
  'session.phpsession.cookiename' => 'SimpleSAML',
  'session.phpsession.savepath' => NULL,
  'session.phpsession.httponly' => true,
  'session.authtoken.cookiename' => 'SimpleSAMLAuthToken',
  'session.rememberme.enable' => false,
  'session.rememberme.checked' => false,
  'session.rememberme.lifetime' => 1209600,
  'memcache_store.servers' => 
  array (
    0 => 
    array (
      0 => 
      array (
        'hostname' => 'localhost',
      ),
    ),
  ),
  'memcache_store.prefix' => '',
  'memcache_store.expires' => 129600,
  'language.available' => 
  array (
    0 => 'en',
    1 => 'no',
    2 => 'nn',
    3 => 'se',
    4 => 'da',
    5 => 'de',
    6 => 'sv',
    7 => 'fi',
    8 => 'es',
    9 => 'fr',
    10 => 'it',
    11 => 'nl',
    12 => 'lb',
    13 => 'cs',
    14 => 'sl',
    15 => 'lt',
    16 => 'hr',
    17 => 'hu',
    18 => 'pl',
    19 => 'pt',
    20 => 'pt-br',
    21 => 'tr',
    22 => 'ja',
    23 => 'zh',
    24 => 'zh-tw',
    25 => 'ru',
    26 => 'et',
    27 => 'he',
    28 => 'id',
    29 => 'sr',
    30 => 'lv',
    31 => 'ro',
    32 => 'eu',
    33 => 'el',
    34 => 'af',
  ),
  'language.rtl' => 
  array (
    0 => 'ar',
    1 => 'dv',
    2 => 'fa',
    3 => 'ur',
    4 => 'he',
  ),
  'language.default' => 'en',
  'language.parameter.name' => 'language',
  'language.parameter.setcookie' => true,
  'language.cookie.name' => 'language',
  'language.cookie.domain' => NULL,
  'language.cookie.path' => '/',
  'language.cookie.lifetime' => 77760000,
  'language.i18n.backend' => 'SimpleSAMLphp',
  'attributes.extradictionary' => NULL,
  'theme.use' => 'default',
  'template.auto_reload' => false,
  'idpdisco.enableremember' => true,
  'idpdisco.rememberchecked' => true,
  'idpdisco.validate' => true,
  'idpdisco.extDiscoveryStorage' => NULL,
  'idpdisco.layout' => 'dropdown',
  'authproc.idp' => 
  array (
    30 => 'core:LanguageAdaptor',
    45 => 
    array (
      'class' => 'core:StatisticsWithAttribute',
      'attributename' => 'realm',
      'type' => 'saml20-idp-SSO',
    ),
    50 => 'core:AttributeLimit',
    99 => 'core:LanguageAdaptor',
  ),
  'authproc.sp' => 
  array (
    90 => 'core:LanguageAdaptor',
  ),
  'metadata.sources' => 
  array (
    0 => 
    array (
      'type' => 'flatfile',
    ),
    1 => 
    array (
      'type' => 'flatfile',
      'directory' => 'metadata-generated',
    ),
  ),
  'metadata.sign.enable' => false,
  'metadata.sign.privatekey' => NULL,
  'metadata.sign.privatekey_pass' => NULL,
  'metadata.sign.certificate' => NULL,
  'store.type' => 'sql',
  'store.sql.dsn' => 'mysql:dbname=volj_test;host=localhost',
  'store.sql.username' => 'volj_volunteers',
  'store.sql.password' => 'yep2HqRE8BGFdq',
  'store.sql.prefix' => 'vol',
  'store.redis.host' => 'localhost',
  'store.redis.port' => 6379,
  'store.redis.prefix' => 'SimpleSAMLphp',
  'idp' => 0,
  'privatekey' => 'server.pem',
  'certificate' => 'server.crt',
  'consent' => '',
);